# Example: API Service with WAF Protection
# This example shows an API service with Alteon SecurePath (WAF) protection

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-waf
  namespace: default
spec:
  selector:
    matchLabels:
      app: api-service-waf
  replicas: 2
  template:
    metadata:
      labels:
        app: api-service-waf
    spec:
      containers:
        - name: api
          image: hashicorp/http-echo:latest
          args:
            - "-text=API Service with WAF Protection"
            - "-listen=:8080"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: api-service-waf
  namespace: default
  annotations:
    # Radware AKC Annotations
    akc.radware.com/lb-algo: leastconnections        # Least connections algorithm
    akc.radware.com/lb-health-check: tcp             # TCP health check
    akc.radware.com/sslpol: api-ssl-policy           # SSL policy for APIs
    akc.radware.com/cert: api-certificate            # API certificate
    akc.radware.com/securepath-policy: api-waf       # WAF policy name
    akc.radware.com/static-ip: "10.0.1.12"           # Static VIP
    akc.radware.com/rate-limiting: "100-per-minute"  # Rate limiting
    akc.radware.com/ddos-protection: "enabled"       # DDoS protection
    akc.radware.com/geo-blocking: "enabled"          # Geo-blocking enabled
    akc.radware.com/whitelist-ips: "10.0.0.0/8"      # IP whitelist
  labels:
    AlteonDevice: "true"                              # Enable AKC processing
spec:
  type: LoadBalancer
  selector:
    app: api-service-waf
  ports:
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: false