#cloud-config
hostname: ${cluster_name}-worker
users:
  - default
  - name: k8s
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7... # Replace with your public key
    shell: /bin/bash
    groups: wheel

package_upgrade: true
packages:
  - container-selinux
  - curl
  - wget
  - git
  - vim
  - htop
  - net-tools

write_files:
  - path: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
  - path: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
  - path: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - path: /etc/containers/storage.conf
    content: |
      [storage]
      driver = "overlay"
      runroot = "/run/containers/storage"
      graphroot = "/var/lib/containers/storage"
      [storage.options]
      additionalimagestores = []
      [storage.options.overlay]
      mountopt = "nodev,metacopy=on"
  - path: /etc/containers/containers.conf
    content: |
      [containers]
      log_driver = "journald"
      log_size_max = 100000000
      cgroup_manager = "systemd"
      [engine]
      cgroup_manager = "systemd"
      events_logger = "journald"
      runtime = "crun"
  - path: /root/join-cluster.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e
      
      # Wait for master node to be ready
      while ! nc -z ${master_ip} 6443; do
        echo "Waiting for master node to be ready..."
        sleep 10
      done
      
      # Get join command from master
      scp -o StrictHostKeyChecking=no k8s@${master_ip}:/tmp/join-command.sh /tmp/join-command.sh
      chmod +x /tmp/join-command.sh
      
      # Join the cluster
      /tmp/join-command.sh
      
      echo "Successfully joined the cluster"

runcmd:
  - modprobe overlay
  - modprobe br_netfilter
  - sysctl --system
  - setenforce 0
  - sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
  - dnf install -y podman crun
  - systemctl enable podman.socket
  - systemctl start podman.socket
  - dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
  - systemctl enable kubelet
  - systemctl start kubelet
  - sleep 120  # Give master time to initialize
  - /root/join-cluster.sh

final_message: "Kubernetes worker node is ready!"