{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akc-controller.secretName" . }}
  namespace: {{ include "akc-controller.namespace" . }}
  labels:
    {{- include "akc-controller.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secret.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}